### ISSUE TITLE
Building in macos-latest

### ISSUE THREAD

**Issue by AsafZoki** [XRTK/activate-unity-license#7]
i can't pass the active licenses steps this is the log i got

`  COMMAND LINE ARGUMENTS:
  /Applications/Unity/Hub/Editor/2019.4.40f1/Unity.app/Contents/MacOS/Unity
  -logfile
  /Users/runner/work/EdgeDK_UNITY/EdgeDK_UNITY/Builds/Logs/ProLicenseActivation-20230829T133900.log
  -quit
  -nographics
  -batchmode
  -username
  ***
  -password
  (hidden)
  -serial
  (hidden)
  Assertion failed on expression: '!projectPath.empty()' 
  (Filename: ./Editor/Src/ProjectUtility.cpp Line: 631)
  
  
  Using Asset Import Pipeline V2.
  DisplayProgressbar: Unity Package Manager
  Rebuilding Library because the asset database could not be found!
  Adding genesis user token GVAD1PNxRYjNlNn43Jq5zVq9LslQ-94k8Ws7BuUgQSg011f[Package Manager] Done resolving packages in 0.10s seconds
  Failed to resolve packages: The file [/Applications/Unity/Hub/Editor/2019.4.40f1/Unity.app/Contents/Packages/manifest.json] cannot be found. No packages loaded.
  
  A re-import of the project may be required to fix the issue or a manual modification of Packages/manifest.json file.`
  
  any idea why it cant see my project path even when i setup it with the right project path in the setup step?

**Comment by StephenHodgson** [comment]
[Just ran some tests here in the repo](https://github.com/XRTK/activate-unity-license/actions/runs/6015979245/job/16318983763). Seems to be working correctly. Take a look at the workflow here and see what might be different in your implementation.

**Comment by StephenHodgson** [comment]
If you require more assistance, hit me up in discord.
